### ISSUE TITLE
Please conform to the one and only version of Python

### ISSUE THREAD

**Issue by FantasticFiasco** [lunjon/gtree#1]
You are building on the version of Python that cannot be named. Please add support for the true Python version, **2**, as soon as possible before the world as we know it implodes on the singularity of the one who cannot be named.

**Comment by lunjon** [comment]
HELO KIND PROGRAMER

tnx 4 showing interest in dis pees of sht software

python 3 is only supportet cus mistype on python install with homebrew. i dont now how 2 noninstall python so axidentaly installed other python, like dis: https://imgs.xkcd.com/comics/python_environment.png

can u pls tell me how install dis version you speek of. else u have 2 wait for my new computer where i install python 2

i try google first but pls help

regrads, me

**Comment by FantasticFiasco** [comment]
I think the conventional way of downgrading to the correct version of Python is to trap a Russian satellite from orbit and have it crash head-on your existing computer. This will temporarily create an opening to another dimension where [Brainfuck](https://en.wikipedia.org/wiki/Brainfuck) is the only existing programming language, and your version of Python, that cannot be named, will be sucked into that dimension, never to return.

Or we can do as you proposed, buy a new computer, and get the *"I've installed the wrong Python version"* discount, that surely must exist.

**Comment by lunjon** [comment]
yes ys yes exelent. considering price of new mac computer i think only reesenable method is d first u mention. the discount only have 0.2 % discount so a new mac cost more than crashin satelite. but problem is i need computer?

maybe free tier aws account + cloud8 work?
